spring.application.name=demo1
spring.datasource.url=jdbc:mysql://localhost:3306/student_management
spring.datasource.username=root
spring.datasource.password=danggxhd123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# T?t banner Spring Boot khi kh?i ??ng
spring.main.banner-mode=off

# T?t toàn b? log m?c ??nh
logging.level.root=OFF
